### PR TITLE
Card percentage fixes.

### LINKED ISSUE #44: Percentage change in cards is incorrect
**Describe the bug**

The percentage change in the cards in the flow chart sometimes displays zero when it shouldn't.

**To Reproduce**
1. Replace `src/data.json` with https://drive.google.com/file/d/1OLenZP9LW_p3SKX1kA7JahL7n6R-nuxk/view?usp=sharing
2. Change `stateCode` to `US_CT` in `src/index.js`
3. Run `yarn start`
3. Open the site and see that all the cards show zero percent change

**Expected behavior**

We'd expect actual value changes to be shown instead, for instance for parole population we expect a value change of -104 and a percentage change of -2%.

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

Screen Shot 2021-02-03 at 9 59 22 AM

Screen Shot 2021-02-03 at 10 04 44 AM

**Desktop (please complete the following information):** running locally

**Additional context**

This file is completely unsorted, maybe that is what is causing this?

### LINKED ISSUE #45: Percentage change shows decimals
**Describe the bug**

Currently percentage change will show all the decimals that are included in the fixture file, instead of limiting to whole percentages

**To Reproduce**
1. Change `stateCode` to `US_CT` (keeping existing checked fixture file)
2. Run `yarn start`
3. Observe long decimals in percentages

**Expected behavior**

This should limit to whole percentages, @hobuobi if there is any preference on rounding vs truncating, or just keep it consistent with the logic for the line graphs.

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

Screen Shot 2021-02-03 at 10 17 05 AM

**Desktop (please complete the following information):** running locally

**Additional context**

### PR DESCRIPTION
**Pull request by Wmaileq**
## Description of the change

- Rounded percents on flow diagram and key insights cards.
- Added support for string `percent_change` and `number_change` fields.

## Type of change

- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #44.
> Closes #45.

### Development

These boxes should be checked by the submitter prior to merging:

- [X] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by Wmaileq** [comment]
@jessex I want to rebase this branch after #37 will be merged.

File: src/index.js [hunk 1]
```diff
@@ -20,13 +20,13 @@ import "react-app-polyfill/stable";
...
 import App from "./App";
-import data from "./data.json";
+import data from "./data-zero.json";
 
 import "./index.scss";
 
 ReactDOM.render(
   <React.StrictMode>
-    <App stateCode="US_CO" data={data} />
+    <App stateCode="US_CT" data={data} />
```
Comment (jessex) [inline src/index.js:29]: Let's revert this back to US_CO before we merge.

File: src/index.js [hunk 2]
```diff
@@ -20,13 +20,13 @@ import "react-app-polyfill/stable";
 import React from "react";
 import ReactDOM from "react-dom";
 import App from "./App";
-import data from "./data.json";
+import data from "./data-zero.json";
```
Comment (jessex) [inline src/index.js:23]: Let's get rid of `data-zero.json` from this repository and revert back to `data.json` before we merge. With this change, it is actually a bit trickier to test this locally because it makes it seem like you've already taken care of Colin's steps to reproduce the bug but it's not 100% clear if that is the case. So reverting back to CO and back to the original data file will make it so I know exactly what to do to test this.

File: src/utils/getNormalizedStateData.js [hunk 3]
```diff
@@ -62,15 +62,17 @@ const getNormalizedStateData = (data, stateCode) => {
...
+        value: toInt(item.value),
         comparedToYear: item.compared_to_year ? toInt(item.compared_to_year) : null,
         comparedToMonth: item.compared_to_month ? toInt(item.compared_to_month) - 1 : null,
-        valueChange: typeof item.value_change === "number" ? item.value_change : null,
-        percentChange: typeof item.percentage_change === "number" ? item.percentage_change : null,
         sourceName: item.source_name,
         sourceUrl: item.source_url,
         reportName: item.report_name,
         sourceCategories: item.raw_source_categories,
+        valueChange: Number.isNaN(Number(item.value_change)) ? null : Number(item.value_change),
```
Comment (jessex) [inline src/utils/getNormalizedStateData.js:72]: These `isNaN` calls will handle strings correctly, right? If the incoming value from the file is a string but it can be parsed into a number, e.g. `"5.3467"`, then it will still be parsed correctly into `5.3467` and not into `NaN`?

**Review by jessex — CHANGES_REQUESTED** [review]
A couple of requests to revert your changes to add in the CT state code and the new data file, so that I can do that myself locally and know exactly what I'm testing. Also one question.

You should be free to rebase this against `main` now, @Wmaileq. Thanks!

File: src/utils/getNormalizedStateData.js (hunk 3 above)
Comment (Wmaileq) [reply src/utils/getNormalizedStateData.js:72]: Yes, it works correctly both with strings and numbers now.

**Review by jessex — APPROVED** [review]
Well done, @Wmaileq
